name: Tests

on:
  - push
  - pull_request

env:
  GOPATH: ${{ github.workspace }}/go

permissions:
  contents: read
  checks: write

jobs:
  test-and-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
        with:
          go-version: '1.22.2'

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          path: ${{ env.GOPATH }}/src/k8s.io/autoscaler

      - name: Apt-get
        run: sudo apt-get install libseccomp-dev -qq

      - name: Prepare
        working-directory: ${{ env.GOPATH }}/src/k8s.io/autoscaler
        run: hack/install-verify-tools.sh
        env:
          GO111MODULE: auto

      - name: Verify
        working-directory: ${{ env.GOPATH }}/src/k8s.io/autoscaler
        run: hack/verify-all.sh -v
        env:
          GO111MODULE: auto

      - name: golangci-lint - vertical-pod-autoscaler
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9
        with:
          args: --timeout=30m
          working-directory: ${{ env.GOPATH }}/src/k8s.io/autoscaler/vertical-pod-autoscaler

      - name: Test
        working-directory: ${{ env.GOPATH }}/src/k8s.io/autoscaler
        run: hack/for-go-proj.sh test
        env:
          GO111MODULE: auto
