permissions:
  contents: read

jobs:
  changes:
    permissions:
      contents: read  # for dorny/paths-filter to fetch a list of changed files
      pull-requests: read  # for dorny/paths-filter to read pull requests
    outputs:
      charts: ${{ steps.filter.outputs.charts }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        with:
          filters: |
            charts:
              - 'charts/**/Chart.yaml'
              - 'charts/**/*'
          token: ${{ secrets.GITHUB_TOKEN }}
  helm-lint-test:
    if: ${{ needs.changes.outputs.charts == 'true' }}
    name: Helm chart
    needs:
      - changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Fetch history
        run: git fetch --prune --unshallow
      - name: Set up chart-testing
        uses: helm/chart-testing-action@0d28d3144d3a25ea2cc349d6e59901c4ff469b3b
      - name: Run chart-testing (lint)
        run: ct lint
      # Only build a kind cluster if there are chart changes to test.
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      - if: steps.list-changed.outputs.changed == 'true'
        name: Create kind cluster
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3
      - if: steps.list-changed.outputs.changed == 'true'
        name: Run chart-testing (install)
        run: ct install
  helm-docs-validate:
    if: ${{ needs.changes.outputs.charts == 'true' }}
    name: Helm Docs
    needs:
      - changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Run helm-docs
        uses: docker://jnorwood/helm-docs:v1.3.0
      - name: Check for changes
        run: git diff --quiet charts/*/README.md

name: Lint and Test Charts
on: pull_request
